app: aws-node-http-api
service: teste
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  # iamRoleStatements: 
  #   - Effect: Allow
  #     Action:
  #       - comprehend:*
  #       Resource: '*'

functions:
  hello:
    handler: src/generate.handler
    events:
      - http:
          path: /capture
          method: POST
          cors: true
