app: aws-node-http-api
service: teste
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.firstLambda
    events:
      - httpApi:
          path: /
          method: get
