app: aws-node-http-api
service: teste
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: src/get.getLambda
    events:
      - httpApi:
          path: /sayhello
          method: get
